### ISSUE TITLE
Identification

### ISSUE THREAD

**Issue by SzotsGabor** [Loev06/Peripheral#4]
Hi,

I am Gabor Szots from the CCRL testing group. I intend to test your engine for our blitz list. May I know your name and country or do you wish to keep them secret?

**Comment by Loev06** [comment]
Hi Gabor,

Thanks for reaching out! I appreciate that you want to include Peripheral in the rating list.
I'm Loek Vissers, from the Netherlands.

Which version(s) of the engine do you intend to test? Peripheral is currently getting quite a lot of improvements, and thus the latest commit (`1.1.3`) is quite a bit stronger than the last release (`1.0.0`). I'm not sure how often I want to/should publish a new release. I noticed that CCRL often tests several versions of the engine against each other, but I do not mind if only the latest version gets added, as I imagine CCRL only tests new versions published, when an initial version is in the list already.

I think my engine should comply with CCRL as-is, but if there are any requirements Peripheral does not conform to, please let me know.

Best regards,
Loek

**Comment by Loev06** [comment]
Hi,

Thanks, and no worries. It's nice that v1 got added, so I have some reference for further improvements.
And yes, I worded my previous message wrongly, I meant to say that CCRL keeps track of the ratings of different versions of an engine, which then could be compared.
